"""Messages for generated character responses."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CharacterSelection:
    """Character selected before character memory is read."""

    character_name: str


@dataclass(frozen=True, slots=True)
class GeneratedCharacterResponse:
    """Structured character response generated by the model."""

    character_name: str
    content: str
    memory_candidates: tuple[str, ...] = ()
    selection_summary: str | None = None
