"""Add team_membership table

Revision ID: 2473e1c2c7de
Revises: 482fd29108a3
Create Date: 2025-12-23 08:37:43.362990

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2473e1c2c7de"
down_revision: str | Sequence[str] | None = "482fd29108a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_memberships",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column(
            "team_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        ),
        sa.Column(
            "user_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        ),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_team_memberships_team_id"), ["team_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_team_memberships_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default="(CURRENT_TIMESTAMP)",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default="(CURRENT_TIMESTAMP)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default="(CURRENT_TIMESTAMP)",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default="(CURRENT_TIMESTAMP)",
        )

    with op.batch_alter_table("team_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_team_memberships_team_id"))

    op.drop_table("team_memberships")
    # ### end Alembic commands ###
