"""add_chats_table_with_tph

Revision ID: 49f4e4f835ac
Revises: 2473e1c2c7de
Create Date: 2026-05-10 15:02:47.418378

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49f4e4f835ac"
down_revision: str | Sequence[str] | None = "2473e1c2c7de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("message_content", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("discord_guild_id", sa.String(length=255), nullable=True),
        sa.Column("discord_channel_id", sa.String(length=255), nullable=True),
        sa.Column("line_user_id", sa.String(length=255), nullable=True),
        sa.Column("line_group_id", sa.String(length=255), nullable=True),
        sa.Column("line_room_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chats_type"), ["type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chats_type"))

    op.drop_table("chats")
    # ### end Alembic commands ###
