"""Add sent_at to chat_messages

Revision ID: 75a66b9621f1
Revises: 69f36b3d445e
Create Date: 2026-01-06 09:06:18.393288

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75a66b9621f1"
down_revision: str | Sequence[str] | None = "69f36b3d445e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True)
        )

    op.execute("UPDATE chat_messages SET sent_at = created_at")

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.alter_column("sent_at", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_column("sent_at")

    # ### end Alembic commands ###
